channels:
- conda-forge
dependencies:
- python=3.12.6
- pip<=24.2
- pip:
  - mlflow==2.16.2
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - psutil==6.0.0
  - scikit-learn==1.4.1.post1
  - scipy==1.12.0
name: mlflow-env
